server_name: BNPP API server
debug: true
# Set issuers to 'null' to accept all JWT from all issuers
issWhitelist:
    - https://accounts.google.com
    - https://authbnpp.meez.io
# If whitelist is empty, use blacklist to exclue issuers
issBlacklist:
tokenExpire: false
redis: redis://:Rtgg7$YU1MDex@localhost:6379/10
